
os:
  - linux
  - osx

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3
    packages:
      - cmake
      - cmake-data

language: cpp

compiler:
    - gcc
    - clang

before_script:
    - mkdir build install rundir
    - cd build
    - cmake .. -DBUILD_FAT=ON -DBUILD_WITHG4=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../install/

script:
    - make install
    - cd ../rundir
    - find ../install
    - ../install/bin/mcplexample_write myfile.mcpl
    - ../install/bin/mcplexample_read myfile.mcpl.gz
    - ../install/bin/mcplexample_filter myfile.mcpl.gz myfile_filtered.mcpl
    - ../install/bin/mcplexample_read myfile_filtered.mcpl.gz
    - ../install/bin/mcpltool myfile.mcpl.gz
    - ../install/bin/mcpltool myfile_filtered.mcpl.gz
    - ../install/bin/mcpltool_fat myfile_filtered.mcpl.gz

