language: cpp

os:
  - linux
  - osx

env:
    - BUILD='Release'
    - BUILD='Debug'

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3
    packages:
      - cmake
      - cmake-data

compiler:
    - gcc
    - clang

before_install:
    - set -e
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                         ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install homebrew/science/geant4; fi
    - set +e

before_script:
    - set -e
    - mkdir build install rundir
    - cd build
    - cmake .. -DBUILD_FAT=ON -DCMAKE_BUILD_TYPE=${BUILD} -DCMAKE_INSTALL_PREFIX=../install/
    - set +e

script:
    - set -e
    - make install
    - cd ../rundir
    - find ../install
    - ../install/bin/mcplexample_write myfile.mcpl
    - ../install/bin/mcplexample_filter myfile.mcpl.gz myfile_filtered.mcpl
    - ../install/bin/mcplexample_read myfile_filtered.mcpl.gz
    - ../install/bin/mcpltool myfile.mcpl.gz
    - ../install/bin/mcpltool myfile_filtered.mcpl.gz
    - ../install/bin/mcpltool_fat myfile_filtered.mcpl.gz
    - set +e
